[workspace]
members = [
    "elfo",
    "elfo-core",
    "elfo-utils",
    "elfo-macros",
    "elfo-test",
    "elfo-configurer",
    "elfo-inspector",
    "elfo-logger",
    "elfo-dumper",
    "elfo-telemeter",
]

[profile.release]
debug = true
