[package]
name = "elfo-eyre"
version = "0.1.0"
description = "Integration with eyre"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
backtrace = "0.3.61"
eyre = "0.6.5"
