[package]
name = "elfo"
version = "0.1.9"
description = "Your next actor system"
keywords = ["actor", "distributed", "tokio"]
authors = ["Paul Loyd <pavelko95@gmail.com>"]
repository = "https://github.com/elfo-rs/elfo"
license = "MIT"
readme = "../README.md"
edition = "2018"

[[test]]
name = "test"
path = "examples/test.rs"
required-features = ["test-util"]

[[example]]
name = "usage"
path = "examples/usage.rs"
required-features = ["full"]

# TODO: ugly, duplicate.
[[example]]
name = "test"
path = "examples/test.rs"
required-features = ["test-util"]

[[test]]
name = "msg_macro"
path = "tests/msg_macro.rs"
required-features = ["test-util"]

[[bench]]
name = "round_trip"
harness = false
required-features = ["full"]

[features]
full = ["elfo-configurer"]
test-util = ["elfo-test", "elfo-core/test-util"]

[dependencies]
elfo-core = { version = "0.1.5", path = "../elfo-core" }
elfo-macros = { version = "0.1", path = "../elfo-macros" }
elfo-test = { version = "0.1", path = "../elfo-test", optional = true }
elfo-configurer = { version = "0.1", path = "../elfo-configurer", optional = true }

[dev-dependencies]
elfo-test = { version = "0.1", path = "../elfo-test" }

anyhow = "1.0.38"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.25"
tracing-subscriber = "0.2.15"
serde = { version = "1.0.120", features = ["derive"] }
toml = "0.5.8"
humantime-serde = "1"
criterion = "0.3.4"
