[package]
name = "elfo-test"
version = "0.1.10"
description = "Test utils"
authors = ["Paul Loyd <pavelko95@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
elfo-macros = { version = "0.1", path = "../elfo-macros" }
elfo-core = { version = "0.1.9", path = "../elfo-core", features = ["test-util"] }
elfo-configurer = { version = "0.1", path = "../elfo-configurer" }

tokio = "1"
serde = { version = "1.0.120", features = ["derive", "rc"] }
serde-value = "0.7.0"
futures-intrusive = "0.4.0"
futures = "0.3.12"
tracing-subscriber = "0.2.15"
